##################################################
# Run Njoku chris Super Linter against code base #
##################################################

---
name:Njoku chris Super Linter
on:
  push:
  pull_request:

jobs:
 run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository 🚦
        uses: actions/checkout@v2

      - name: Run GitHub Super Linter 🚀
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH:'/'
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
